### ISSUE TITLE
Moodle 4.5, icon dark mode not shown

### ISSUE THREAD

**Issue by marcosgtz** [EduardoKrausME/moodle-local_boost_dark#1]
Hello, your plugin is very nice, I 've been looking for something like this for years :)

I installed it, but the icon to change between light and dark mode not appears anywhere.

I opened the file dark.js, and I think you can change a line

From this: $(".navbar .simplesearchform").before(
To this: $("#usernavigation").prepend(
I opened the file dark.js, and I think you could change a line

From this: $(".navbar .simplesearchform").before(
To this: $("#usernavigation").prepend(
I tested it in my moodle 4.5 and worked it

Thank you

**Comment by eduardokraus** [comment]
Hello! 😊

Thank you so much for your feedback and for suggesting the code adjustment! I'm glad to know the plugin met your expectations. I've updated the plugin with the modification you mentioned. If you have more ideas or suggestions, I’ll be more than happy to hear them! 🚀

Thank you for your support and for sharing your experience. 🌟
