### ISSUE TITLE
Typo in getting/setting user preference

### ISSUE THREAD

**Issue by rjnl** [EduardoKrausME/moodle-local_boost_dark#2]
When getting the user preference, value of "theme_mode" is being fetched: https://github.com/EduardoKrausME/moodle-local_boost_dark/blob/17194e34d3c3e75fe26a64669983b6afbf2ff18a/classes/core_hook_output.php#L53C9-L53C66
But when setting the user preference, value of "layout" is being saved: https://github.com/EduardoKrausME/moodle-local_boost_dark/blob/17194e34d3c3e75fe26a64669983b6afbf2ff18a/classes/external/userpreference.php#L58C9-L58C48

So the mode defaults to light mode on page reload.

**Comment by eduardokraus** [comment]
Resolvido
